config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'groups#index'
  resources :users, only: [:edit, :update]
  resources :groups, only: [:new, :create, :edit, :update] do
  resources :messages, only: [:index, :create]
  end

end



# ユーザー編集機能を実装するため、まずはルーティングを定義していきましょう。
# ユーザーの編集に必要なルーティングは:edit, :updateなので、routes.rbに追記しておきましょう。

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users
  has_many :messages
  
  validates :name, presence: true, uniqueness: true

  def show_last_message
    if (last_message = messages.last).present?
      if last_message.content?
        last_message.content
      else
        '画像が投稿されています'
      end
    else
      'まだメッセージはありません。'
    end
  end
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :group
  belongs_to :user

  # validates :content, presence: true, unless: :image?

  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :group_users
  has_many :groups, through: :group_users
  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  def index
  end

  def new
    @group = Group.new
    @group.users << current_user
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to root_path, notice: 'グループを作成しました'
    else
      render :new
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    if @group.update(group_params)
      redirect_to group_messages_path(@group), notice: 'グループを更新しました'
    else
      render :edit
    end
  end

  private
  def group_params
    params.require(:group).permit(:name, user_ids: [])
  end
  
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_group

  def index
    @message = Message.new
    @messages = @group.messages.includes(:user)
  end

  def create
    @message = @group.messages.new(message_params)
    if @message.save
      redirect_to group_messages_path(@group), notice: 'メッセージが送信されました'
    else
      @messages = @group.messages.includes(:user)
      flash.now[:alert] = 'メッセージを入力してください。'
      render :index
    end
  end

  private

  def message_params
    params.require(:message).permit(:content, :image).merge(user_id: current_user.id)
  end

  def set_group
    @group = Group.find(params[:group_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end


# editアクションでは必要になるインスタンス変数はないので、
# アクションを定義するだけで大丈夫です。

# Userモデルの更新を行うupdateアクションは、保存できた場合、
# できなかった場合で処理を分岐しています。

# updateできた場合は「true」が、できなかった場合は「false」が返り値として戻ってきます。
# それを利用して、if文での分岐ができます。

# 今回の場合は、current_user.updateに成功した場合、rootにリダイレクトし、
# 失敗した場合、editのビューを再度描画する、という記述になっています。

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/_form.html.haml
= form_for group do |f|
  - if group.errors.any?
    .chat-group-form__errors
      %h2= "#{group.errors.full_messages.count}件のエラーが発生しました。"
      %ul
        - group.errors.full_messages.each do |message|
          %li= message
  .chat-group-form__field
    .chat-group-form__field--left
      = f.label :name, class: 'chat-group-form__label'
    .chat-group-form__field--right
      = f.text_field :name, class: 'chat__group_name chat-group-form__input', placeholder: 'グループ名を入力してください'
  .chat-group-form__field.clearfix
    / この部分はインクリメンタルサーチ（ユーザー追加の非同期化のときに使用します
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      %label.chat-group-form__label{:for => "chat_group_チャットメンバー"} チャットメンバー
    .chat-group-form__field--right
      / グループ作成機能の追加時はここにcollection_check_boxesの記述を入れてください
      = f.collection_check_boxes :user_ids, User.all, :id, :name
      / この部分はインクリメンタルサーチ（ユーザー追加の非同期化のときに使用します
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
    .chat-group-form__field--right
      = f.submit class: 'chat-group-form__action-btn'

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  = render partial: 'form', locals: { group: @group }

app/views/groups/index.html.haml
.wrapper
  = render 'messages/side_bar'

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  = render partial: 'form', locals: { group: @group }

app/views/layouts/_notifications.html.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ChatSpace3
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/notifications'
    = yield

app/views/messages/_main_chat.html.haml
.chat-main
  .main-header
    .left-header
      .left-header__name
        = @group.name
      %ul.left-header__members
        Member:
        %li.left-header__member
          - @group.users.each do |user|
            = user.name
    .right-header 
      .right-header__botton
        = link_to "Edit", edit_group_path(@group.id)

  .messages
    = render @messages
    -# .message
    -#   .message__upper-info
    -#     .message__upper-user
    -#       メンバー
    -#     .message__upper-date
    -#       日付け
    -#   .message-text
    -#     メッセージ
    -#   .message__upper-info
    -#     .message__upper-user
    -#       メンバー
    -#     .message__upper-date
    -#       日付け
    -#   .message-text
    -#     メッセージ
    -#   .message__upper-info
    -#     .message__upper-user
    -#       メンバー
    -#     .message__upper-date
    -#       日付け
    -#   .message-text
    -#     メッセージ

  .form
    = form_for [@group, @message] do |f|
      .input-box 
        = f.text_field :content, class: 'input-box__text', placeholder: 'type a message'
        = f.label :image, class: 'input-box__image' do
          = fa_icon 'image'
          = f.file_field :image, class: 'hidden'
      = f.submit 'Send', class: 'submit-btn'

app/views/messages/_message.html.haml
.message
  .message__upper-info
    .message__upper-user
      = message.user.name
    .message__upper-date
      = message.created_at.strftime("%Y年%m月%d日 %H時%M分")
  .message-text
    - if message.content.present?
      = message.content
    = image_tag message.image.url, class: 'lower-message__image' if message.image.present?

app/views/messages/_side_bar.html.haml
.side-bar
  .header
    %h3.header__name
      = current_user.name
    %ul.header__lists
      %li.header__lists__edit 
        = link_to new_group_path do
          = fa_icon "edit"
      %li.header__lists__cog
        = link_to edit_user_path(current_user.id) do
          = fa_icon "cog" 

  .groups
    - current_user.groups.each do |group|
      .group
        = link_to group_messages_path(group) do 
          .group__name
            = group.name
          .group__message
            = group.show_last_message
          .group__name
            = group.name
          .group__message
            = group.show_last_message
          .group__name
            = group.name
          .group__message
            = group.show_last_message

app/views/messages/index.html.haml
.wrapper
  = render "side_bar"
  = render "main_chat"

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      
      %h5 アカウントの編集
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'      
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'